export const USER_INFO = "USER_INFO";
export const USER_SETTING = "USER_SETTING";

export const BOOK_LIST = "BOOK_LIST";
export const BOOK_CATEGORY = "BOOK_CATEGORY";
export const BOOK_LIST_BY_CATEGORY = "BOOK_LIST_BY_CATEGORY";
export const BOOK_LIST_TODAY_RECOMMEND = "BOOK_LIST_TODAY_RECOMMEND";
export const BOOK_LIST_LATEST_POPU = "BOOK_LIST_LATEST_POPU";
export const BOOK_SEARCH_RESULT = "BOOK_SEARCH_RESULT";
