language: go
sudo: required

go:
  - 1.x

services:
  - docker
  - postgresql
  - redis-server

before_install:
  - docker run -d -p 6379:6379 redis:alpine
  - psql -c "CREATE DATABASE novel;" -U postgres
  - psql -c "CREATE USER tree WITH PASSWORD 'mypwd';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE novel to tree;" -U postgres

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - dep ensure
  - make test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t novel .
  - docker tag novel $DOCKER_USERNAME/novel
  - docker push $DOCKER_USERNAME/novel
  - docker images